### ISSUE TITLE
Launching tests not running

### ISSUE THREAD

**Issue by deybhayden** [JakeBecker/vscode-elixir-ls#26]
It looks like my phx.server is starting with this task, and then I get the following log:

```
        {
            "type": "mix_task",
            "name": "mix test",
            "request": "launch",
            "task": "test",
            "taskArgs": [
                "--trace"
            ],
            "env": {
                "MIX_ENV": "test"
            },
            "startApps": true,
            "projectDir": "${workspaceRoot}",
            "requireFiles": [
                "test/**/test_helper.exs",
                "test/**/*_test.exs"
            ],
            "excludeModules": [
                "Bcrypt.Base"
            ]
        }
```

```
(Debugger) Task failed because an exception was raised:
    ** (Mix.Error) The database for Foobar.Repo couldn't be dropped: got ArgumentError with message "argument error" while retrieving Exception.message/1 for %Postgrex.Error{connection_id: 26931, message: nil, postgres: %{code: :object_in_use, detail: "There are 20 other sessions using the database.", file: "dbcommands.c", line: "862", message: "database \"foobar_test\" is being accessed by other users", pg_code: "55006", routine: "dropdb", severity: "ERROR", unknown: "ERROR"}}
        (mix) lib/mix.ex:291: Mix.raise/1
        (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir) lib/enum.ex:675: Enum.each/2
        (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
        (mix) lib/mix/task.ex:333: Mix.Task.run_alias/3
        (mix) lib/mix/task.ex:266: Mix.Task.run/2
```

**Comment by JakeBecker** [comment]
It's weird that it's failing to format the exception, but `There are 20 other sessions using the database.` looks like it explains your problem. Likely there's another test session or server running somewhere else against the same database. Try quitting VS Code and your terminal session, then re-opening it and try again.

**Comment by deybhayden** [comment]
Same issue - I quit completely, nothing running and still get the above error message. 🤷‍♂️
