### ISSUE TITLE
Failure to source .env

### ISSUE THREAD

**Issue by jhaddow** [JakeBecker/vscode-elixir-ls#45]
I keep getting this error that causes the ElixirLS server to crash. Any fixes?

```
** (Mix.Config.LoadError) could not load config config/dev.exs
    ** (SourceENVException) You need to source your .env first
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
[Info  - 08:52:02] Connection to server got closed. Server will restart.
** (Mix.Config.LoadError) could not load config config/dev.exs
    ** (SourceENVException) You need to source your .env first
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
[Info  - 08:52:03] Connection to server got closed. Server will restart.
** (Mix.Config.LoadError) could not load config config/dev.exs
    ** (SourceENVException) You need to source your .env first
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
[Info  - 08:52:03] Connection to server got closed. Server will restart.
** (Mix.Config.LoadError) could not load config config/dev.exs
    ** (SourceENVException) You need to source your .env first
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
[Info  - 08:52:04] Connection to server got closed. Server will restart.
** (Mix.Config.LoadError) could not load config config/dev.exs
    ** (SourceENVException) You need to source your .env first
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
[Error - 08:52:05] Connection to server got closed. Server will not be restarted.
```

**Comment by JakeBecker** [comment]
There was a bug in ElixirLS in which config files might get loaded before the mixfile and cause failures. It should be fixed now. Can you reproduce this in the latest release?

**Comment by jhaddow** [comment]
I am not able to reproduce this bug in the latest release. Thanks!
