### ISSUE TITLE
Erlang error: :nif_library_not_loaded

### ISSUE THREAD

**Issue by StasD** [JakeBecker/vscode-elixir-ls#68]
Hello,
I'm getting this error when debugging the code:
```
Started ElixirLS debugger
Compiling 1 file (.ex)
(Debugger) Task failed because an exception was raised:
    ** (ErlangError) Erlang error: :nif_library_not_loaded
        :erlang.nif_error(:nif_library_not_loaded)
        (esqlite) esqlite3_nif.erl:53: :esqlite3_nif.start/0
        (esqlite) esqlite3.erl:59: :esqlite3.open/2
        (my_utils_elixir) Elixir.MyUtilsElixir.SqliteUtils.erl:15: 
        MyUtilsElixir.SqliteUtils.get_conn/1
        my_utils_elixir) Elixir.MyUtilsElixir.erl:47: MyUtilsElixir.hello/0
        (elixir) src/elixir.erl:233: :elixir.eval_forms/4
        (elixir) lib/code.ex:192: Code.eval_string/3
        (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
```

It's failing where I create connection to SQLite database file using Sqlitex library:
```
{:ok, conn} = Sqlitex.open(path)
```

When running the code without debugging, it runs just fine. Debugging of simpler Elixir code also worked fine for me.

Here is the configuration from launch.json:
```
    "configurations": [
        {
            "type": "mix_task",
            "name": "mix (Default task)",
            "request": "launch",
            "projectDir": "${workspaceRoot}",
            "task": "run",
            "taskArgs": [
                "--eval",
                "MyUtilsElixir.hello"
            ]
        },
```
Help would be very appreciated!

**Comment by JakeBecker** [comment]
Change your config to this:
```
        {
            "type": "mix_task",
            "name": "mix (Default task)",
            "request": "launch",
            "projectDir": "${workspaceRoot}",
            "task": "run",
            "taskArgs": [
                "--eval",
                "MyUtilsElixir.hello"
            ],
            "excludeModules": [":esqlite3_nif"]
        }
```

Then it should probably work. You can't step through the NIF code but you can debug other modules.

**Comment by StasD** [comment]
With `"excludeModules": [":esqlite3_nif"]` it worked! Thanks!
