### ISSUE TITLE
Failed to start in Windows 10 with WSL and asdf

### ISSUE THREAD

**Issue by vheathen** [JakeBecker/vscode-elixir-ls#73]
I'm using WSL with Ubuntu and asdf as an Elixir package manager.
I've been using vscode-elixir for a while and is able to use Elixir from WSL via a set of bat\ps1 files (actually these files are no more than wrapper around bash -lc; more details [here](https://github.com/fr1zle/vscode-elixir/issues/109)).

But when I try to use the same method on ElixirLS I get the next bunch of errors in the VSCode development console:

```
[Extension Host] Error: Channel has been closed
	at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:591)
	at e.appendLine (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:225)
	at LanguageClient.info (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-languageclient\lib\client.js:1574:28)
	at LanguageClient.handleConnectionClosed (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-languageclient\lib\client.js:1875:18)
	at LanguageClient.handleConnectionClosed (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at Socket.<anonymous> (C:\Users\vlad\.vscode\extensions\JakeBecker.elixir-ls-0.2.19\node_modules\vscode-jsonrpc\lib\messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
```

Please let me know if you need more information. Also I not sure this is the correct repo...

**Comment by holtalanm** [comment]
i was having a similar issue (unable to run this using asdf elixir), but my issue was related to elixir not being on the PATH for bash (since I use fish shell).

running the bash setup commands for asdf fixed it for me:
```
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
```

Im not saying this will work for you, as I know you are having a completely different problem.  Just wanted to leave this here in case anyone else stumbles upon this with the same problem I had.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
