### ISSUE TITLE
ElixirLS in Windows crashes when project is in D:\

### ISSUE THREAD

**Issue by sadesyllas** [JakeBecker/vscode-elixir-ls#9]
First of all, great work! 👍 

I would also very much like to see this great project get merged with vscode-elixir which would provide an ever greater toolset on VS Code for Elixir.

In `Windows 10`, I get the following error when loading an elixir file in `D:\my_project` as seen in the built in the `OUTPUT` console in `VS Code 1.13.1`:

```
[Info  - 11:11:49 π.μ.] Child Logger.ErrorHandler of Supervisor Logger.Supervisor started
Pid: #PID<0.76.0>
Start Call: Logger.Watcher.watcher(:error_logger, Logger.ErrorHandler, {true, true, 500})
Restart: :permanent
Shutdown: 5000
Type: :worker
[Info  - 11:11:49 π.μ.] Application logger started at :nonode@nohost
[Info  - 11:11:49 π.μ.] Child ElixirLS.LanguageServer.Builder of Supervisor ElixirLanguageServer.Supervisor started
Pid: #PID<0.81.0>
Start Call: ElixirLS.LanguageServer.Builder.start_link(ElixirLS.LanguageServer.Builder)
Restart: :permanent
Shutdown: 5000
Type: :worker
[Info  - 11:11:49 π.μ.] Child ElixirLS.LanguageServer.Server of Supervisor ElixirLanguageServer.Supervisor started
Pid: #PID<0.82.0>
Start Call: ElixirLS.LanguageServer.Server.start_link(ElixirLS.LanguageServer.Server)
Restart: :permanent
Shutdown: 5000
Type: :worker
[Info  - 11:11:49 π.μ.] Child ElixirLS.IOHandler of Supervisor ElixirLanguageServer.Supervisor started
Pid: #PID<0.83.0>
Start Call: ElixirLS.IOHandler.start_link(ElixirLS.LanguageServer.Server, [name: ElixirLS.LanguageServer.IOHandler])
Restart: :permanent
Shutdown: 5000
Type: :worker
[Info  - 11:11:49 π.μ.] Application language_server started at :nonode@nohost
[Error - 11:11:49 π.μ.] Elixir Language Server terminated abnormally because an exception was raised:
    ** (File.Error) could not set current working directory to "c:/my_project": no such file or directory
        (elixir) lib/file.ex:1144: File.cd!/1
        (language_server) lib/language_server/server.ex:235: ElixirLS.LanguageServer.Server.handle_request/2
        (language_server) lib/language_server/server.ex:89: ElixirLS.LanguageServer.Server.handle_call/3
        (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
[Info  - 11:11:50 π.μ.] Connection to server got closed. Server will restart.
```

This goes on for 3 times in 5 seconds (the console has been truncated) and then the relevant Supervisor dies as expected.

I am guessing that `handle_request` at `elixir-ls/apps/language_server/lib/language_server/server.ex:228` get a *wrong* path as input when called from `handle_call` at line 87.

**Comment by JakeBecker** [comment]
Thanks for the bug report. I was handling Windows paths incorrectly. I thought `Path.absname("/D:/path")` would yield `"d:/path"` but it actually ends up as `"c:/path"`. Can you update your plugin to v0.0.9 and let me know if it's fixed?

As to merging with vscode-elixir, it's possible in the future once ElixirLS is more stable. Glad you like the project!

**Comment by sadesyllas** [comment]
@JakeBecker I can confirm that I do not have this problem anymore on my windows pc.

Thanks for your prompt reply!
